CREATE TABLE `apiKeys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`keyHash` varchar(128) NOT NULL,
	`keyPrefix` varchar(12) NOT NULL,
	`name` varchar(100) NOT NULL,
	`permissions` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`rateLimit` int NOT NULL DEFAULT 100,
	`lastUsedAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`revokedAt` timestamp,
	CONSTRAINT `apiKeys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `b2bDeliveries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`externalOrderId` varchar(200) NOT NULL,
	`trackingCode` varchar(64) NOT NULL,
	`status` enum('pending','assigned','pickup_enroute','picked_up','in_transit','delivered','cancelled','failed') NOT NULL DEFAULT 'pending',
	`pickupAddress` text NOT NULL,
	`pickupContactName` varchar(200),
	`pickupContactPhone` varchar(30),
	`pickupReadyAt` timestamp,
	`deliveryAddress` text NOT NULL,
	`deliveryContactName` varchar(200),
	`deliveryContactPhone` varchar(30),
	`deliveryNotes` text,
	`packageWeight` int,
	`packageDimensionsL` int,
	`packageDimensionsW` int,
	`packageDimensionsH` int,
	`packageFragile` boolean DEFAULT false,
	`packageDescription` text,
	`preferredMode` enum('drone','terrestrial','any') DEFAULT 'any',
	`urgency` enum('standard','express','scheduled') DEFAULT 'standard',
	`scheduledAt` timestamp,
	`assignedPilotId` int,
	`deliveryMode` enum('drone','terrestrial'),
	`estimatedArrival` timestamp,
	`actualPickupAt` timestamp,
	`actualDeliveryAt` timestamp,
	`quotedPrice` decimal(10,2),
	`finalPrice` decimal(10,2),
	`currency` varchar(3) DEFAULT 'RON',
	`cancelledBy` enum('partner','system','pilot'),
	`cancellationReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `b2bDeliveries_id` PRIMARY KEY(`id`),
	CONSTRAINT `b2bDeliveries_trackingCode_unique` UNIQUE(`trackingCode`)
);
--> statement-breakpoint
CREATE TABLE `webhookEndpoints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`url` varchar(500) NOT NULL,
	`events` text NOT NULL,
	`secret` varchar(128) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`failureCount` int NOT NULL DEFAULT 0,
	`lastTriggeredAt` timestamp,
	`lastSuccessAt` timestamp,
	`lastFailureReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `webhookEndpoints_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webhookLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`webhookEndpointId` int NOT NULL,
	`deliveryId` int,
	`event` varchar(100) NOT NULL,
	`payload` text NOT NULL,
	`responseStatus` int,
	`responseBody` text,
	`success` boolean NOT NULL DEFAULT false,
	`attemptNumber` int NOT NULL DEFAULT 1,
	`sentAt` timestamp NOT NULL DEFAULT (now()),
	`respondedAt` timestamp,
	CONSTRAINT `webhookLogs_id` PRIMARY KEY(`id`)
);
